### ISSUE TITLE
Unable to select / copy text content in tables

### ISSUE THREAD

**Issue by IconoclastXYZ** [IAEA-NDS/IsotopeBrowser#1]
Hi,
Once I drill down to an isotope of an element from the periodic table (Element -> Isotope List (labelled Chart) -> Isotope) or from the Chart I get a very useful page of data, but long pressing, which would normally allow text selection on Android, does not work so there is no easy way to then select and copy the data (eg. Mass, Qa) to use in a calculation.

**Comment by mverpelli** [comment]
That would be indeed useful. Placed in the to do list
