### ISSUE TITLE
APK Download

### ISSUE THREAD

**Issue by IzzySoft** [IAEA-NDS/IsotopeBrowser#2]
First, thanks for providing your app open-source-wise! Unfortunately, it seems the only place the "average Jane & Joe" can get the app to install it on their devices is a walled garden demanding registration and its tracking stuff on said devices. Would you consider providing the APK here for download? Best practice would be to attach it to its corresponding [release](https://github.com/IAEA-NDS/IsotopeBrowser/releases).

Thanks in advance!

**Comment by mverpelli** [comment]
Indeed, thanks for the suggestion

**Comment by mverpelli** [comment]
Done for v5.38.83

**Comment by IzzySoft** [comment]
Thanks a lot! Building upon that: with the next sync around 6 pm UTC, your app now becomes [available in my repo](https://apt.izzysoft.de/packages/iaea.nds.nuclides/), so folks using an [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) of their choice and having my repo enabled have an easy way to discover, install and update the app (they'll receive notifications about new releases, which are automatically fetched by my updater within 24h of your making its APK available at a new release).

Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to accompany the Google one in your Readme and link there :smiley: 

Btw: From what I can see (and my library checker reports), your app would be eligible for listing at [F-Droid.org](https://f-droid.org/), a repo with higher reputation than mine (as F-Droid builds apps from source, thus making sure the provided APK really matches what it says to be built from). If you wish, I can help you getting it in there (disclosure: I'm also one of the F-Droid maintainers).

**Comment by mverpelli** [comment]
Okay thanks , I will revert back to you about this when I am back in the office beginning of September

**Comment by Coool** [comment]
@mverpelli, do you plan to release 5.45.87 (160) version on [GitHub](https://github.com/IAEAOrg/IsotopeBrowser/releases) available at [Google Play](https://play.google.com/store/apps/details?id=iaea.nds.nuclides)?

**Comment by IzzySoft** [comment]
Wait, and where's the source code for that? Did the app go proprietary?
